### ISSUE TITLE
how to get model file by http url?

### ISSUE THREAD

**Issue by chenkaiC4** [rastapasta/react-native-gl-model-view#3]
hi, @rastapasta how to get model file by http url ? now the model prop need value which is the name of file included by xcode.

**Comment by rastapasta** [comment]
hey @chenkaiC4 - not yet possible, but would be with a bridge to [GLModel::modelWithData](https://github.com/nicklockwood/GLView/blob/master/GLView/Models/GLModel.m#L424-L427).

feel more than welcome to implement it, otherwise it will be tackled when I'm able to reprioritize this project + give it some android love ;)

**Comment by Dylan-at-LION** [comment]
If anyone is still interested in doing this I was able to pull it off with react-native-fetch-blob: https://github.com/joltup/react-native-fetch-blob

Like so:

In componentDidMount():

`
const dir = RNFetchBlob.fs.dirs.MainBundleDir; 

let modelState = {
    testTexture: false,
    testModel: false
};

RNFetchBlob
.config({
    path : dir + '/yourModel.obj'
})`
.fetch('GET', 'https://host.com/yourModel.obj', { // must be https
    //some headers ..
})
.then((res) => {
    modelState.testModel = 'testModel3.obj';

    RNFetchBlob
        .config({
            path : dir + '/yourTexture.png'
        })
        .fetch('GET', 'https://host.com/dylan_at_lion/yourTexture.png', { // must be https
            //some headers ..
        })
        .then((res) => {
            modelState.testTexture = 'yourTexture.png';
            this.setState( modelState );
        });
});
`

The model state object is kind of redundant and ideally you would extract your filename from the URL rather than hardcoding it, but this should get the point across. Just use `this.state.testModel` and `this.state.testTexture` for props to your ModelView component.

**Comment by Dylan-at-LION** [comment]
@dmitriy-karpenko I loaded the texture off of a WordPress site I use for testing. I tried imgur first, but it resizes images such that it breaks the texture (ruins "power of 2" image dimensions).

Are you sure you're using a public facing link on Dropbox? i.e. if you open the link in an incognito browser does it prompt a log in?

Unfortunately, I don't have my original code with me at the moment, but here are some other possibilities:

1. Don't try to initialize the model until the texture is already loaded.
2. Make sure you're saving it to the same directory I used above, it's the only one that works for this library at the moment.

The app just dies or does it provide an error message of some kind?

**Comment by Dylan-at-LION** [comment]
@dmitriy-karpenko Now that I re-read this "'getting it with link with raw=1' in the ending" is probably the issue. If you're not loading from a public facing direct image source i.e. `dropbox.com/image.jpg` it won't work. Not `dropbox.com/image.jpg?raw=1`

**Comment by rastapasta** [comment]
It's now a feature thanks to @Cawfree's #20 - cheers & enjoy!
