### ISSUE TITLE
Does not compile react-native 0.53 android

### ISSUE THREAD

**Issue by loic-lopez** [rastapasta/react-native-gl-model-view#7]
Please update android code, in iOS it compile

Error: 

` 
react-native-gl-model-view/android/src/main/java/com/rnglmodelvie/RNGLModelViewPackage.java:20: error: method does not override or implement a method from a supertype
`

**Comment by PatriceVignola** [comment]
It's a [known issue](https://github.com/rastapasta/react-native-gl-model-view/issues/1) that has been noticed before. I will quote was I said back then:

> The createJSModules() method was removed in react-native 0.47, but the peerDependencies in react-native-gl-model-view's package.json specifies react-native >= 0.41. If we remove the @override, the module will stop working for versions >= 0.41 and < 0.47.

But since many people are having this problem, I will create a pull request tonight that will fix this issue. I think people who wish to upgrade to the latest version of the react-native-gl-model-view module should also upgrade their project to the latest version of react-native, like most react-native modules recommend.

Therefore, I will update the minimum react-native version to 0.47 and post another comment when the pull request has been created. You will then have the option to cherry pick my change until the PR has been merged, or simply wait a few days/weeks for the merge.

**Comment by PatriceVignola** [comment]
Sorry for the delay. Upgrading the module to 0.54 from 0.41 is 13 versions worth of changes and it took more time than I expected. I was also pretty busy with other stuff. I created a pull request [over here](https://github.com/rastapasta/react-native-gl-model-view/pull/8). You can give it a look if you want and pull my branch to make sure it's working on your system. Don't hesitate to contact me if you have any problems. I faced a of problems myself during the lengthy upgrade process so I can probably help you out. I will probably be more available in the following days or weeks and babysit this PR.

**Comment by rastapasta** [comment]
@PatriceVignola can confirm that it works on 0.54 - many many thanks for your work & efforts!
